# Generated by Django 3.2.8 on 2021-11-05 00:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='observacoes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
