# Generated by Django 3.2.8 on 2021-11-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Nascimento'),
        ),
    ]
