# Generated by Django 3.2.8 on 2021-11-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_medico_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='paciente',
        ),
    ]
