# Generated by Django 3.2.8 on 2021-11-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_medico_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hospital.medico'),
            preserve_default=False,
        ),
    ]
