# Generated by Django 3.2.8 on 2021-11-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_paciente_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
    ]
