# Generated by Django 3.2.8 on 2021-11-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='atendimento',
            field=models.ManyToManyField(to='hospital.Atendimento'),
        ),
    ]
